/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.example.Ecosystem;
import org.example.dsa.ArrayBag;
import org.example.persona.Customer;
import org.example.persona.DelPartner;
import org.example.utils.DBConn;
import org.example.utils.Utils;

/**
 *
 * @author marri
 */
public class SignUpDPJPanel extends javax.swing.JPanel {

    Ecosystem es;
    javax.swing.JPanel CardSequencePanel;
    private static final String EMAIL_REGEX = "^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,4}$";

    
    /**
     * Creates new form SignUpDPJPanel
     */
    public SignUpDPJPanel(Ecosystem es, JPanel clp) {
        this.es=es;
        this.CardSequencePanel = clp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        txtPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SignUp Delivery Partner");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 90);

        jLabel3.setText("Password");
        add(jLabel3);
        jLabel3.setBounds(150, 280, 100, 30);

        jLabel6.setText("Email");
        add(jLabel6);
        jLabel6.setBounds(160, 200, 120, 16);

        jLabel7.setText("Phone number");
        add(jLabel7);
        jLabel7.setBounds(150, 240, 120, 16);
        add(txtPhone);
        txtPhone.setBounds(290, 240, 120, 22);
        add(txtEmail);
        txtEmail.setBounds(290, 200, 120, 22);
        add(txtName);
        txtName.setBounds(290, 160, 120, 22);

        btnSignUp.setText("Sign up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        add(btnSignUp);
        btnSignUp.setBounds(220, 350, 120, 30);
        add(txtPassword);
        txtPassword.setBounds(290, 280, 120, 22);

        jLabel4.setText("Name");
        add(jLabel4);
        jLabel4.setBounds(160, 160, 100, 16);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(60, 400, 72, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        Connection conn = DBConn.establishConnection();
         // Checking for phone number length
            if (txtPhone == null || txtPhone.getText().length() != 10) {
                System.out.println(txtPhone.getText().length());
               JOptionPane.showMessageDialog(this, "Mobile phone number must be 10 digits long.");
               return;
            }
            // Checking for name length
            if (txtName == null || txtName.getText().isEmpty() || txtName.getText().length() > 20) {
                 JOptionPane.showMessageDialog(this,"Name cannot be empty and should not exceed 20 characters.");
              return;
            }

            // Checking for email length and format
            if (txtEmail == null || txtEmail.getText().isEmpty() || txtEmail.getText().length() > 50 || !txtEmail.getText().matches(EMAIL_REGEX)) {
                 JOptionPane.showMessageDialog(this,"Invalid email format. Please provide a valid email.");
              return;
            }

            // Checking for password
            if (txtPassword == null || txtPassword.getText().isEmpty()) {
                 JOptionPane.showMessageDialog(this,"Password cannot be empty.");
              return;
            }
            if(es.getDPDirectory().findDPByEmail(txtEmail.getText()) != null){
                JOptionPane.showMessageDialog(this,"Email Already exists!");                    
                return;
            }
//            ArrayBag<DelPartner> dps = DBConn.getDPFromDB(conn);
//            DelPartner[] dpList;
//            dpList = (DelPartner[]) java.lang.reflect.Array.newInstance(DelPartner.class, dps.getCurrentSize());
//            System.arraycopy(dps.toArray(), 0, dpList, 0, dps.getCurrentSize());
//            for(DelPartner dp : dpList){
//                if(dp.isEmailMatch(txtEmail.getText())){
//                 JOptionPane.showMessageDialog(this,"Email Already exists!");                    
//                return;
//            }
//            }
        try {
            CallableStatement callableStatement = conn.prepareCall("{call create_delivery_partner(?,?,?,?)}");
            callableStatement.setString(1, txtName.getText());
            callableStatement.setInt(2, Integer.parseInt(txtPhone.getText()));
            callableStatement.setString(3, txtEmail.getText());
            callableStatement.setString(4, txtPassword.getText());
            callableStatement.execute();
            es.refreshDPs();
            JOptionPane.showMessageDialog(this, "Delivery partner is created!");
        } catch (SQLException ex) {
            Logger.getLogger(SignUpDPJPanel.class.getName()).log(Level.SEVERE, ex.toString(), ex);
        }catch(NumberFormatException nEx){
            System.out.println(nEx.toString());
            JOptionPane.showMessageDialog(this, "Phone number is inCorrect!");
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel); 
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
